const GENIUS_ENDPOINT = "https://api.genius.com";
const CLIENT_ID =
  "ctokZwUfFN3tRZvAF3508DuFP96uTHbzrUzO1qRr1afr_uHooGGpQpYyyPtctNXz";
const CLIENT_SECRET =
  "kHUtzfUEv40H27yPcM47aSyilIFmKEh7CRwKmsQs9u_l4gusJ9SqN4qAv8VK1pOYxFwPlrrXsteVa8JEEHWoxw";
const ACCESS_TOKEN =
  "EGD5O9WVYIyagmEQBfAgmp-WAt7VcMjME59wm4pM7BZ2fzwrii1vAIfOKZ31WK_0";

export { GENIUS_ENDPOINT, CLIENT_ID, CLIENT_SECRET, ACCESS_TOKEN };
